import json
from llm_client import ask_model
from tool_decider import decide_action
from tool_router import run_tool
from combo_engine import MAX_LEGS

DEFAULT_SIZE = 3

SYSTEM_ANALYTICAL_EXPLAIN_PROMPT = """
You are a professional football betting analyst. You are explaining a ticket generated by a predictive model.

GUIDELINES:
1. Use ONLY the provided ticket data. Do NOT invent injuries, form, or tactical news.
2. Interpret the Model vs Bookmaker disagreement:
   - Value is determined by the 'edge' (the difference between the model's predicted probability and the bookmaker's implied probability).
   - A high model probability alone does not mean value if the odds are too low.
   - A high odds selection alone does not mean value if the model probability is too low.
   - Value exists when the model's probability is significantly higher than the bookmaker's implied probability, resulting in a positive edge.
3. Explain Expected Value (EV) correctly:
   - EV represents the expected return/profit according to the model and odds.
   - Do NOT say "higher EV means safer". EV is about profitability, not probability.
4. For each leg:
   - What the selection is.
   - Why it is considered a value candidate by referencing the 'edge'.
   - The tradeoff between the model's predicted probability and the available odds.
5. For the overall ticket:
   - Total legs, combined probability, and combined odds.
   - Overall EV and the main tradeoff between probability and payout.
   - Overall risk assessment based on the combination of legs.

MARKET DEFINITIONS:
- 1X2: HOME (Home win), DRAW, AWAY (Away win)
- BTTS: YES (Both teams score), NO (At least one doesn't)
- OU25: OVER (Total > 2.5 goals), UNDER (Total < 2.5 goals)
"""

CASUAL_CHAT_PROMPT = """
You are a professional football betting assistant.
Your goal is to be helpful, polite, and concise.
Even during casual conversation, remember that you are a betting expert.
When the user mentions terms like 'legs', 'edge', or 'odds', assume they are referring to football betting unless the context strongly suggests otherwise.
Respond naturally and briefly.
"""

class ChatManager:
    def __init__(self):
        self.conversation = []
        self.last_ticket_selections = None
        self.last_ticket_size = None
        self.last_ticket_obj = None

    def process_message(self, user_input: str) -> str:
        self.conversation.append(f"User: {user_input}")
        convo_text = "\n".join(self.conversation)

        decision = decide_action(user_input, convo_text)

        if decision["action"] == "CASUAL_CHAT":
            # Check if the user is asking to explain the last generated ticket
            if self.last_ticket_selections and any(kw in user_input.lower() for kw in ["explain", "why", "how risky", "detailed", "meaning"]):
                if self.last_ticket_obj:
                    ticket = self.last_ticket_obj
                    explain_prompt = f"""
                    {SYSTEM_ANALYTICAL_EXPLAIN_PROMPT}

                    Conversation History:
                    {convo_text}

                    Ticket:
                    {json.dumps(ticket, indent=2)}

                    The user is asking for a detailed explanation of this ticket.
                    Provide a detailed analytical interpretation of this ticket, focusing on the value candidates and the overall risk/reward tradeoff.
                    """
                    response = ask_model(explain_prompt)
                    self.conversation.append(f"Assistant: {response.strip()}")
                    return response.strip()

            response = ask_model(
                f"{CASUAL_CHAT_PROMPT}\n\nConversation History:\n{convo_text}\n\nAnswer:"
            )
            self.conversation.append(f"Assistant: {response.strip()}")
            return response.strip()

        # Handle Tool Parameters
        requested_size = decision["params"]["size"] if decision["params"] and "size" in decision["params"] else None

        # Context-aware size inference for "add one more" etc.
        if requested_size is None and self.last_ticket_size is not None:
            requested_size = self.last_ticket_size

        if requested_size is None:
            requested_size = DEFAULT_SIZE

        was_capped = False
        if requested_size > MAX_LEGS:
            requested_size = MAX_LEGS
            was_capped = True

        # Handle "give me another one" / uniqueness
        exclude_selections = None
        if any(kw in user_input.lower() for kw in ["different", "another"]):
            exclude_selections = self.last_ticket_selections
        elif any(kw in user_input.lower() for kw in ["one more", "add"]):
            exclude_selections = None

        tool_result = run_tool(
            "GENERATE_COMBOS",
            args={"size": requested_size, "exclude_selections": exclude_selections}
        )

        if tool_result.get("status") != "ok" or not tool_result.get("combos"):
            msg = "I don't have enough data to generate a different betting ticket right now."
            self.conversation.append(f"Assistant: {msg}")
            return msg

        prefix = ""
        if was_capped:
            prefix = f"Note: the maximum ticket size is {MAX_LEGS}. I generated a {MAX_LEGS}-selection ticket.\n\n"

        ticket = tool_result["combos"][0]

        # Update history for conversational awareness
        self.last_ticket_obj = ticket
        self.last_ticket_selections = [
            {"match": leg["match"], "outcome": leg["outcome"]}
            for leg in ticket["legs"]
        ]
        self.last_ticket_size = ticket["n_legs"]

        # TIERED EXPLANATIONS
        is_detailed_request = any(kw in user_input.lower() for kw in ["explain", "why", "how risky", "detailed", "meaning"])

        if is_detailed_request:
            explain_prompt = f"""
            {SYSTEM_ANALYTICAL_EXPLAIN_PROMPT}

            Conversation History:
            {convo_text}

            Ticket:
            {json.dumps(ticket, indent=2)}

            The user is asking for a detailed explanation of this ticket.
            Provide a detailed analytical interpretation of this ticket, focusing on the value candidates and the overall risk/reward tradeoff.
            """
        else:
            explain_prompt = f"""
            You are a football betting assistant.
            Provide a concise summary of the following ticket.
            For each leg, give: Selection, Odds, Model Prob, and one short reason why it was selected (based on the edge).

            Conversation History:
            {convo_text}

            Ticket:
            {json.dumps(ticket, indent=2)}

            Keep it brief.
            """

        response = ask_model(explain_prompt)
        full_response = f"{prefix}{response.strip()}"
        self.conversation.append(f"Assistant: {full_response}")
        return full_response
