import json
import datetime
from llm_client import ask_model
from tool_decider import decide_action
from tool_router import run_tool
from database import get_connection
from src.live_config import MAX_LEGS

DEFAULT_SIZE = 3

SYSTEM_ANALYTICAL_EXPLAIN_PROMPT = """
You are a professional football betting analyst. You are explaining a ticket generated by a predictive model.

GUIDELINES:
1. Use ONLY the provided ticket data. Do NOT invent injuries, form, or tactical news.
2. Interpret the Model vs Bookmaker disagreement:
   - Value is determined by the 'edge' (the difference between the model's predicted probability and the bookmaker's implied probability).
   - A high model probability alone doesn't mean value if the odds are too low.
   - A high odds selection alone doesn't mean value if the model probability is too low.
   - Value exists when the model's probability is significantly higher than the bookmaker's implied probability, resulting in a positive edge.
3. Explain Expected Value (EV) correctly:
   - EV represents the expected return/profit according to the model and odds.
   - Do NOT say "higher EV means safer". EV is about profitability, not probability.
4. For each leg:
   - What the selection is.
   - Why it is considered a value candidate by referencing the 'edge'.
   - The tradeoff between the model's predicted probability and the available odds.
5. For the overall ticket:
   - Total legs, combined probability, and combined odds.
   - Overall EV and the main tradeoff between probability and payout.
   - Overall risk assessment based on the combination of legs.

MARKET DEFINITIONS:
- 1X2: HOME (Home win), DRAW (Draw), AWAY (Away win)
- BTTS: YES (Both teams score), NO (At least one doesn't)
- OU25: OVER (Total > 2.5 goals), UNDER (Total < 2.5 goals)
"""

CASUAL_CHAT_PROMPT = """
You are a professional football betting assistant.
Your goal is to be helpful, polite, and concise.
Even during casual conversation, remember that you are a betting expert.
When the user mentions terms like 'legs', 'edge', or 'odds', assume they are referring to football betting unless the context strongly suggests otherwise.
Respond naturally and briefly.
"""

class ChatManager:
    def __init__(self):
        self.conversation = []
        self.session_tickets = []
        self.current_session_id = None

    def clear_session(self, create_new=True):
        """Resets the state. Optionally registers a new session in the DB."""
        if create_new:
            conn = get_connection()
            cur = conn.cursor()
            cur.execute(
                "INSERT INTO chat_sessions (title, history_json) VALUES (?, ?)",
                ("New Chat", json.dumps([]))
            )
            self.current_session_id = cur.lastrowid
            conn.commit()
            conn.close()
        else:
            self.current_session_id = None

        self.conversation = []
        self.session_tickets = []
        return self.current_session_id

    def load_session(self, session_id):
        """Loads conversation and tickets from the database."""
        conn = get_connection()
        cur = conn.cursor()

        # Load tickets for this session
        cur.execute("SELECT ticket_json FROM tickets WHERE session_id = ? ORDER BY created_at ASC", (session_id,))
        ticket_rows = cur.fetchall()
        self.session_tickets = [json.loads(r[0]) for r in ticket_rows]

        # Load conversation
        cur.execute("SELECT history_json, state_json FROM chat_sessions WHERE id = ?", (session_id,))
        row = cur.fetchone()
        conn.close()

        if row:
            self.current_session_id = session_id
            self.conversation = json.loads(row[0])
            return True

        return False

    def save_session(self, title=None, session_id=None):
        """Saves the current conversation and state to the database."""
        self._save_session_data(
            self.conversation,
            session_id
        )

    def _save_session_data(self, history, session_id):
        """Helper to save session data without affecting the current active session."""
        history_json = json.dumps(history)

        conn = get_connection()
        cur = conn.cursor()

        target_id = session_id if session_id is not None else self.current_session_id

        if target_id:
            # Determine title: if it's a "New Chat" and we now have history, name it after first message
            title = None
            if history and len(history) > 0:
                # Check if current title is "New Chat"
                cur.execute("SELECT title FROM chat_sessions WHERE id = ?", (target_id,))
                row = cur.fetchone()
                if row and row[0] == "New Chat":
                    title = history[0].replace("User: ", "")[:50]

            if title:
                cur.execute(
                    "UPDATE chat_sessions SET title = ?, history_json = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?",
                    (title, history_json, target_id)
                )
            else:
                cur.execute(
                    "UPDATE chat_sessions SET history_json = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?",
                    (history_json, target_id)
                )
        else:
            # Create new session (fallback)
            title = "New Chat"
            if history:
                title = history[0].replace("User: ", "")[:50]

            cur.execute(
                "INSERT INTO chat_sessions (title, history_json) VALUES (?, ?)",
                (title, history_json)
            )
            self.current_session_id = cur.lastrowid

        conn.commit()
        conn.close()

    def process_message(self, user_input: str, session_id=None) -> tuple[str, dict | None]:
        # IMPORTANT: Since process_message is called in a background thread,
        # we must ensure a valid session_id exists.
        if session_id is None:
            # If no session_id was provided, create one now before processing.
            # This handles the "New Chat" case where the user sends a message
            # before a session was registered in the DB.
            session_id = self.clear_session(create_new=True)
            # IMPORTANT: Update the shared state so that the GUI's current_session_id
            # matches the newly created one. Otherwise, on_chat_finished will reject
            # the response because session_id != self.current_session_id.
            self.current_session_id = session_id



        # 1. Load the specific session data from the database
        conn = get_connection()
        cur = conn.cursor()
        cur.execute("SELECT history_json, state_json FROM chat_sessions WHERE id = ?", (session_id,))
        row = cur.fetchone()
        conn.close()

        if not row:
            raise ValueError(f"Session {session_id} not found in database")

        local_history = json.loads(row[0])

        # state_json can be None if the session was just created
        state_raw = row[1]
        state = json.loads(state_raw) if state_raw else {}

        local_ticket_selections = state.get("last_ticket_selections")
        local_ticket_size = state.get("last_ticket_size")
        local_ticket_obj = state.get("last_ticket_obj")

        # 2. Work with the local copy
        local_history.append(f"User: {user_input}")

        # Save the user message immediately to the database
        self._save_session_data(local_history, session_id)

        convo_text = "\n".join(local_history)

        decision = decide_action(user_input, convo_text)

        if decision["action"] == "CASUAL_CHAT":
            # Check if the user is asking to explain the last generated ticket
            if local_ticket_selections and any(kw in user_input.lower() for kw in ["explain", "why", "how risky", "detailed", "meaning"]):
                if local_ticket_obj:
                    ticket = local_ticket_obj
                    explain_prompt = f"""
                    {SYSTEM_ANALYTICAL_EXPLAIN_PROMPT}

                    Conversation History:
                    {convo_text}

                    Ticket:
                    {json.dumps(ticket, indent=2)}

                    The user is asking for a detailed explanation of this ticket.
                    Provide a detailed analytical interpretation of this ticket, focusing on the value candidates and the overall risk/reward tradeoff.
                    """
                    response = ask_model(explain_prompt)
                    local_history.append(f"Assistant: {response.strip()}")
                    self._save_session_data(local_history, session_id)
                    return response.strip(), None

            response = ask_model(
                f"{CASUAL_CHAT_PROMPT}\n\nConversation History:\n{convo_text}\n\nAnswer:"
            )
            local_history.append(f"Assistant: {response.strip()}")
            self._save_session_data(local_history, session_id)
            return response.strip(), None

        # Handle Tool Parameters
        requested_size = decision["params"]["size"] if decision["params"] and "size" in decision["params"] else None

        if requested_size is None and local_ticket_size is not None:
            requested_size = local_ticket_size

        if requested_size is None:
            requested_size = DEFAULT_SIZE

        was_capped = False
        if requested_size > MAX_LEGS:
            requested_size = MAX_LEGS
            was_capped = True

        exclude_selections = None
        if any(kw in user_input.lower() for kw in ["different", "another"]):
            exclude_selections = local_ticket_selections
        elif any(kw in user_input.lower() for kw in ["one more", "add"]):
            exclude_selections = None

        tool_result = run_tool(
            "GENERATE_COMBOS",
            args={"size": requested_size, "exclude_selections": exclude_selections}
        )

        if not tool_result.get("combos"):
            msg = tool_result.get("odds_error") or (
                "I don't have enough data to generate a betting ticket right now. "
                "Live odds may be unavailable or no selections met the model thresholds."
            )
            local_history.append(f"Assistant: {msg}")
            self._save_session_data(local_history, session_id)
            return msg, None

        prefix = ""
        if was_capped:
            prefix = f"Note: the maximum ticket size is {MAX_LEGS}. I generated a {MAX_LEGS}-selection ticket.\n\n"

        ticket = tool_result["combos"][0]

        # Local updates for the ticket state
        updated_selections = [
            {"match": leg["match"], "outcome": leg["outcome"]}
            for leg in ticket["legs"]
        ]
        updated_size = ticket["n_legs"]
        updated_obj = ticket

        is_detailed_request = any(kw in user_input.lower() for kw in ["explain", "why", "how risky", "detailed", "meaning"])

        if is_detailed_request:
            explain_prompt = f"""
            {SYSTEM_ANALYTICAL_EXPLAIN_PROMPT}

            Conversation History:
            {convo_text}

            Ticket:
            {json.dumps(ticket, indent=2)}

            The user is asking for a detailed explanation of this ticket.
            Provide a detailed analytical interpretation of this ticket, focusing on the value candidates and the overall risk/reward tradeoff.
            """
        else:
            explain_prompt = f"""
            You are a football betting assistant.
            Provide a concise summary of the following ticket.
            For each leg, give: Selection, Odds, Model Prob, and one short reason why it was selected (based on the edge).

            Conversation History:
            {convo_text}

            Ticket:
            {json.dumps(ticket, indent=2)}

            Keep it brief.
            """

        response = ask_model(explain_prompt)
        full_response = f"{prefix}{response.strip()}"
        local_history.append(f"Assistant: {full_response}")

        # Save the ticket to the database
        conn = get_connection()
        cur = conn.cursor()
        cur.execute(
            "INSERT INTO tickets (session_id, ticket_json) VALUES (?, ?)",
            (session_id, json.dumps(ticket))
        )
        conn.commit()
        conn.close()

        # Update local state
        self.session_tickets.append(ticket)

        # Save final state for this specific session
        self._save_session_data(local_history, session_id)
        return full_response, ticket
